apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: Y2FsY3VzZXI=  # calcuser (base64 encoded)
  password: Y2FsY3Bhc3N3b3Jk  # calcpassword (base64 encoded)
  database: Y2FsY3VsYXRvcmRi  # calculatordb (base64 encoded)